version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 10s
      timeout: 3s
      retries: 5
