name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run lint (pylint)
        run: poetry run pylint app tests

      - name: Run pytest
        run: poetry run pytest
